### ISSUE TITLE
create gig

### ISSUE THREAD

**Issue by pablomikel** [amp-music/Website#23]
- [ ] event title (title will be artist if left blank)
- [ ] date (calendar selection tool for gig date)
- [ ] time
- [ ] genre1 (inherited but venue can edit)
- [ ] genre2 (inherited but venue can edit)
